repos:
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: v19.1.7
      hooks:
          - id: clang-format

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
            types_or: [c, c++]
          - id: end-of-file-fixer
            types_or: [c, c++]
          - id: check-merge-conflict
          - id: mixed-line-ending
            types_or: [c, c++]
            args: ["--fix=lf"]
            description: Forces to replace line ending by the UNIX 'lf' character
